### PR TITLE
Emp

### PR DESCRIPTION
**Pull request by empurvis**
fixed the requests!

### CODE REVIEW

**Comment by empurvis** [comment]
darn, I accidentally committed another uncompleted draft file for the visualizations. it shouldn't matter, I'll put in another pull request when I finish that up

**Review by youngdjn — CHANGES_REQUESTED** [review]
Most of the way there, but there is still code outside of functions. Sorry I was unclear. I didn't mean just remove comments, but actually remove all the code except what's in the functions. It's redundant with what's in the functions anyway (it was just used to develop the functions, but is now fully encapsulated in the accompanying functions). When this code file gets sourced upon loading the `ofo` package, the only way to access the functionality will be by calling the functions. Standalone code lines are extraneous.

**Comment by empurvis** [comment]
ah gotcha. should be fixed now.

**Review by youngdjn — APPROVED** [review]
Awesome, looks great -- go ahead and merge! Then pull from main so you get all the other updates since you branched.

**Pull request merged**
